### ISSUE TITLE
Improved testing using HCP Consul/Vault with their Terraform providers

### ISSUE THREAD

**Issue by nadenf** [hashicorp/terraform-provider-hcp#132]
### Description

There needs to be improved support for the following use case:

1) Provision a Consul or Vault cluster in Hashicorp Cloud.
2) Add entries (e.g. hosts/secrets) in those respective clusters using Terraform.

Right now this provider is unusable for this and would be good to have additional E2E testing to ensure it works.

### New or Affected Resource(s)

* hcp_consul_cluster
* hcp_vault_cluster

### References

* #123
* #124 
* #131

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bcmdarroch** [comment]
Hi @nadenf! Thanks for submitting this issue. I'll bring this to our product team.

To clarify, are the issues listed under references the complete list of blockers that you've found?

**Comment by nadenf** [comment]
@bcmdarroch .. I haven't even got to the point of connecting the two so there could be more.

**Comment by bcmdarroch** [comment]
Would you be able to provide more detail on what you are trying to accomplish?

Based on the information you've provided, the team thinks this might be a private networking issue. Writing to the clusters requires a private network peered to an HVN. You can do this following this [peering guide](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/guides/peering). In order to write to the cluster, your private network will also need a [TF agent](https://www.terraform.io/docs/cloud/agents/index.html) installed.

Note: We will be releasing some changes to our networking resources (see [announcement](https://discuss.hashicorp.com/t/action-required-pin-current-version-of-hcp-terraform-provider-to-account-for-upcoming-changes-to-networking-resources/24995)), if you'd like to try out the version to be released 6/7/21.

**Comment by nadenf** [comment]
This issue is about having automated testing in place to cover all of the scenarios involved in using HCP with the Consul/Vault providers. To make sure this use case is always supported.

Nothing to do with networking.

**Comment by bcmdarroch** [comment]
I'm closing this issue, as we now have the following tutorials that demonstrate the best practices for working with the HCP, Vault, and Consul providers. 

**Vault**
- https://learn.hashicorp.com/tutorials/cloud/vault-codify-mgmt?in=vault/cloud-ops 
- https://learn.hashicorp.com/tutorials/vault/apply-codified-oss-vault-hcp-terraform?in=vault/terraform-hcp-vault

**Consul**
- https://learn.hashicorp.com/tutorials/consul/hcp-gs-deploy?in=consul/get-started-hcp
- https://learn.hashicorp.com/tutorials/cloud/consul-end-to-end-overview?in=consul/cloud-deploy-automation

**Comment by iniinikoski** [comment]
Sorry to late-comment this - but @nadenf might have a point here. We've been facing the same problem.

Long story short is this: we have a Terraform module which spins up a Vault cluster with HCP provider. Within this same code and Terraform run, we'd like to connect to this HCP Vault cluster (admin token is fine) to provision Vault resources. True E2E-testing for a Terraform-module then (with a clean ephemeral HCP Vault cluster).

@nadenf is this what you originally meant...?

Anyway, I'll try to build a sample case what I'd expect to happen (maybe it's a new issue then) - depends how @nadenf responds of course. What I've understood is, Terraform doesn't like to work properly between two different providers - and with our initial tests a while ago, this was the case.

Quoting Arnold: "I'll be back". :) But with a friendly tone :)

**Comment by iniinikoski** [comment]
@nadenf sorry for the possible spam but I found another one from Vault provider which could help us: https://github.com/hashicorp/terraform-provider-vault/pull/1541

I believe...
