### ISSUE TITLE
Add computed output "auth_method_id" to "hcp_boundary_cluster" resource

### ISSUE THREAD

**Issue by mocofound** [hashicorp/terraform-provider-hcp#396]
### Description

After using the HCP Terraform provider to create an 'hcp_boundary_cluster' resource, there is no easy way to grab the initial generated password auth method auth_method_id that is generated for use with the originally supplied username and password values.

Unfortunately, this leads to not being able to cleanly automate the cluster configuration using the Boundary Terraform Provider, as the boundary provider requires the auth_method_id for authentication:

```hcl
#First, create HCP Boundary Cluster
resource "hcp_boundary_cluster" "boundary_cluster" {
  cluster_id = var.cluster_id
  username   = var.password
  password   = var.username
}

#Second, authenticate to the cluster using boundary provider
provider "boundary" {
  addr                            = "https://1232a069-b529-42ad-ba84-823cb5c3b4d7.boundary.hashicorp.cloud"
  auth_method_id                  = "ampw_1234567890" # NOT OUTPUT BY HCP PROVIDER ABOVE
  password_auth_method_login_name = var.username   
  password_auth_method_password   = var.password
}
```

### New or Affected Resource(s)

* hcp_boundary_cluster

### Potential Terraform Configuration

```hcl
output "boundary_password_auth_method_id" {
  value = hcp_boundary_cluster.boundary_cluster.auth_method_id
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by PPacent** [comment]
Adding a little more context for those who may be unfamiliar:

When you deploy HCP Boundary, the initial global scope username/password is set as the primary auth method. 

With the latest change in Boundary's 1.1.6 TF provider, the primary auth method is now used by default. This means it is no longer necessary to pass the auth method id in order to deploy and configure HCP Boundary in a single TF run.

So while this issue is closed - it might be more accurate to consider this (adding auth method id to the output of HCP Boundary deployment) as "won't do" because of 1.1.6's improved workaround.
